### ISSUE TITLE
Create a Link Card component

### ISSUE THREAD

**Issue by heykc** [Now-Loading/ChainLetter#15]
## Description
This link card will display a single story link. It should contain the following pieces of data

## Linked Issues
Subtask of #2 

## Acceptance Criteria
- [ ] Chain's title
- [ ] story link's content
- [ ] author name
- [ ] author profile image (colored circle for now)
- [ ] continue chain button

## Notes
Continue chain button should load all links connected to this link and display either all or some of them in some fashion.
