### ISSUE TITLE
Create mockups of homepage 

### ISSUE THREAD

**Issue by heykc** [Now-Loading/ChainLetter#5]
### Description
Design some mockups to visualize the style and structure of the homepage of our site. 

### Subtask of
#2 - _As a user I want to view a list of chain letters_

### Acceptance Criteria:
- [ ] should include basic nav
  - [ ] Title
  - [ ] home link
  - [ ] about link
  - [ ] login/ sign up link
- [ ] list of first-link stories

**Comment by heykc** [comment]
If someone wants to work on this, let me know. I can take some time to discuss the overall flow of the site in more detail to help you come up with some ideas for the design.

**Comment by KevinW90** [comment]
There's a Figma file where you can edit/suggest changes to the homepage design.
-Please do not change previous work that is not yours without discussing it first.
  *You're welcome to create/duplicate a frame and make adjustments on that one if you'd like.*
-Please label your frames/sections you create.
-Please author your comments on work. (EX. "Some comment on a design choice. --KevinW)

https://www.figma.com/file/msThfGRsvbNmw9dirrnwsj/Untitled

**Comment by KevinW90** [comment]
There is a [Figma file](https://www.figma.com/file/msThfGRsvbNmw9dirrnwsj/home-page-mocks?node-id=0%3A1) with some designs for the homepage. You can add comments on specific elements. I'd love to hear feedback and suggestions for what can be improved upon. Please give a reason for your suggestions as well.

Keep in mind they are lo-fi grey-box wireframe mock-ups.

**Comment by heykc** [comment]
Looks good. I think Screen 3 had the most promise. Next steps should be as follows:
- [ ] come up with a few mocks of card layout using the data info we discussed
  - story title
  - story content
  - author name
  - author image
  - total children
  - overall chain rating
  - view story button
- [ ] screens with the card layouts repeated
- [ ] provide some color variation in next mockups

**Comment by KevinW90** [comment]
3 Card layouts have been chosen from 11 made.
Desktop (1440x1024) and mobile (375x812) screens tile those 3 designs.
Red (#ff0000) is the current accent color.
Secondary action color is a lite-grey (#ebebeb)
Mockup status has changed to being logged in. 
Might change the author name to red (primary) to relay clickability.
Might have the menu icon (hamburger) on mobile be in a lite-grey (secondary) box with rounded corners (border-radius).

**Comment by KevinW90** [comment]
Thanks for the comments on the Figma file @heykc. I did some revisions based on those. There is a new frame in Card Tiling with some new card designs and a layout concept. Please view the Figma file and leave some comments.
