### ISSUE TITLE
Setup Firebase services

### ISSUE THREAD

**Issue by heykc** [Now-Loading/ChainLetter#6]
Get all initial services built out through Firebase. 

### Subtask of
#4 _Account signup/signin functionality_

### Acceptance Criteria
- [x] Create Auth
  - [x] allow users to sign up via email/pass
- [x] Create firestore
  - [x] should have collection for story links
  - [x] should have collection for user extra info
