### ISSUE TITLE
Connect Firebase services to frontend

### ISSUE THREAD

**Issue by heykc** [Now-Loading/ChainLetter#7]
### Description
Connect all necessary firebase services to chain letter app. 

### Subtask of
#4 _Account signin/signup functionality_

### Acceptance Criteria
- [ ] create firebase config
- [ ] create auth wrapper around app
- [ ] create hooks for login/signup
